version: "3.9"

services:
    frontend:
        build:
            target: build
            # args:
            #     - NODE_ENV=test
        volumes:
            - /home/runner/work/receipe-app-api/receipe-app-api/frontend:/app
