version: "3.9"

services:
    backend:
        # volumes:
        #     - ./backend/app:/app
        user: "1001:998"
        environment:
            - DB_HOST: ${{ env.DB_HOST }}
            - DB_NAME: ${{ env.DB_NAME }}
            - DB_USER: ${{ env.DB_USER }}
            - DB_PASS: ${{ secrets.DB_PASSWORD }}


    frontend:
        build:
            target: build
            # args:
            #     - NODE_ENV=test
        volumes:
            - ./frontend:/app # basically this file is down to a compose.build.yml now. Rename it - if cicd has other requirements.
            # - /app/node_modules
            # - /app/build
            # - ./frontend/node_modules:/app/node_modules 
        # working_dir:
        #     /app
        # entrypoint:
        #     - /bin/sh
