version: "3.9"

services:
    frontend:
        build:
            target: build
            # args:
            #     - NODE_ENV=development
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - ./frontend/node_modules:/app/node_modules
        command:
            npm run dev