version: "3.9"

services:
    backend:
        ports:
            - "8000:8000"
        command:
            sh -c "python manage.py runserver 0.0.0.0:8000"
        env_file:
            - ./backend/.env

    db:
        volumes:
            - dev-db-data:/var/lib/postgresql/data/

    frontend:
        build:
            target: build
            # args:
            #     - NODE_ENV=development
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - ./frontend/node_modules:/app/node_modules
        command:
            npm run dev

volumes:
    dev-db-data: