version: "3.9"

services:
    backend:
        build:
            args:
                - DEV=true
        ports:
            - "8000:8000"
        command:
            sh -c "python manage.py runserver 0.0.0.0:8000"

    frontend:
        build:
            target: build
            # args:
            #     - NODE_ENV=development
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - ./frontend/node_modules:/app/node_modules
        command:
            npm run dev