version: "3.9"

services:
    backend:
        ports:
            - "8000:8000"
        command:
            sh -c "python manage.py runserver 0.0.0.0:8000"
            # sh -c  "python manage.py wait_for_db &&
            #         python manage.py runserver 0.0.0.0:8000"
            # sh -c  "python manage.py wait_for_db &&
            #         python manage.py migrate &&
            #         python manage.py runserver 0.0.0.0:8000"
            # python manage.py wait_for_db &&
        env_file:
            - ./backend/.env

    db:
        volumes:
            - dev-db-data:/var/lib/postgresql/data/
        # env_file:
        #     - ./backend/.env
        # command:
        #     sh -c "env"
        # environment:
        #     - POSTGRES_PASSWORD=${DB_PASS}

    frontend:
        build:
            target: build
            # args:
            #     - NODE_ENV=development
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - ./frontend/node_modules:/app/node_modules
        command:
            npm run dev

volumes:
    dev-db-data: