version: "3.9"

services:
    frontend:
        build:
            target: build
            # args:
            #     - NODE_ENV=test
        volumes:
            - ./frontend:/app # basically this file is down to a compose.build.yml now. Rename it - if cicd has other requirements.
            # - ./frontend/node_modules:/app/node_modules
        command:
            - cp -r /app/node_modules /app/build /app/.frontend/
